import type { Metadata } from "next";
import { Amatic_SC, Alegreya } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/shared/header";

const amatic_SC = Amatic_SC({
  style: "normal",
  weight: ["400", "700"] as const
});

const alegreya = Alegreya({
  style: ["normal", "italic"],
  weight: ["400","500","600","700","800","900"] as const
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${amatic_SC} ${alegreya} antialiased`}>
        <main className="min-h-screen">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
